apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tenure

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ui-deployment.yaml
  - subscription-service-deployment.yaml
  - queue-service-deployment.yaml
  - kyc-service-deployment.yaml
  - payout-service-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: tenure-platform
  app.kubernetes.io/managed-by: kustomize
